steps:
  - name: 'maven:3-openjdk-18-slim'
    id: SonarCloud
    entrypoint: bash
    args:
      - '-c'
      - |
        mvn verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=codada \
          -Dsonar.projectKey=codada_gcp-devsecops-repo \
          -Dsonar.token=$$SONAR_TOKEN
    secretEnv:
      - 'SONAR_TOKEN'

  - name: 'maven:3-openjdk-18-slim'
    id: SnykSCA
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "SNYK_TOKEN=$$SNYK_TOKEN"
        mvn snyk:test -fn
    secretEnv:
      - 'SNYK_TOKEN'

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/cloudbuild-sonar-token/versions/latest'
      env: 'SONAR_TOKEN'
    - versionName: 'projects/$PROJECT_ID/secrets/cloudbuild-snyk-token/versions/latest'
      env: 'SNYK_TOKEN'